DEFAULT_TICKERS = ["SPY", "QQQ"]
DEFAULT_EXPIRATION_WEIGHTS = [0.5, 0.3, 0.2]
DEFAULT_MAX_DISTANCE = 30
DEFAULT_NUM_LEVELS = 15

NY_TIMEZONE = "America/New_York"

DATA_CACHE_DIR = "data_cache"
SETTINGS_FILE = f"{DATA_CACHE_DIR}/app_settings.json"
REFRESH_STATUS_FILE = f"{DATA_CACHE_DIR}/refresh_status.json"